# Generated by Django 4.0.2 on 2022-05-13 14:32

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_img_delete_uploadimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='img2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Training_Img', models.ImageField(upload_to=home.models.custom2)),
            ],
        ),
        migrations.AlterField(
            model_name='img',
            name='Training_Img',
            field=models.ImageField(upload_to=home.models.custom),
        ),
    ]
