# Generated by Django 4.0.2 on 2022-05-14 13:42

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_img2_alter_img_training_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='img3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Testing_Img', models.ImageField(upload_to=home.models.custom3)),
            ],
        ),
    ]
